name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  ruby:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.0'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the specs
      run: bundle exec rspec

  node:
    runs-on: ubuntu-latest
    name: Node build

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - run: npm ci
    - run: npm run build
    - name: Show any unstaged changes in dist
      run: git diff dist
    - name: Throw if dist is not commited
      run: git diff-index --quiet HEAD dist
